### ISSUE TITLE
Intermittant Usage

### ISSUE THREAD

**Issue by doubledgedboard** [flamewave000/discord-overlay#1]
Thanks so much for this app, it's incredible and solved an issue I sorely wanted solved.

When it works, it's amazing!

However, I just wanted to report that most of the time it does _not_ work. Discord seems to fail to hook to the overlay host.

It consistently hooks to other applications/games, so I know the discord overlay itself still works.

**Comment by doubledgedboard** [comment]
Mostly wondering if there's some kind of debug info or anything I can surface.

It NEVER works anymore.

**Comment by flamewave000** [comment]
Unfortunately there's no debug info on the Overlay side that I can capture. Discord does this Auto-Magically with nothing on my side. The way it seems to work is that Discord detects the app has a DirectX Interface, and then grabs onto that interface to draw its own stuff on top of it. I haven't had any major issues, there have been some occasions where Discord would recognize that the "game" is playing but not draw anything. I usually just restart the Discord Overlay and it works after a few moments.

**Comment by doubledgedboard** [comment]
Thanks for the response. That's why I'm trying to figure out some kind of debug info. It's been extremely intermittent for when it works.

When it works though, it's the BEST THING EVER!! Thanks again for writing this.

**Comment by flamewave000** [comment]
I've done a little bit of looking into this. It seems that since my program is not officially registered with Discord, you get this kind of delay. Sometimes Discord will also just stop trying if the program has been started and stopped very quickly a few times. So one way I fix it is to close Discord and the app, then relaunch Discord, then after it has fully loaded, relaunch the Overlay. Also double check that the overlay hasn't been disabled in Discord's Game Activity settings.

**Comment by doubledgedboard** [comment]
@flamewave000 Following up on this issue, I discovered the root cause.

I use MSI Afterburner which uses Riva Tune Statistics Server (RSSS) which hooks 3D applications for displaying performance metrics.

After disabling RSSS for Discord Overlay, the overlay works consistently every time I launch it.

**Comment by flamewave000** [comment]
Awesome, I'm happy you were able to find the root cause. Thanks for updating me 👍🏽
