### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by neromidnight** [flamewave000/discord-overlay#7]
The app just stays gray the whole time, sometimes something appears and then it says that the window size is too small. It's probably beacuse my screen is 4k but you should really solve that issue

**Comment by jrettsch** [comment]
same issue with my 4k monitors

**Comment by flamewave000** [comment]
@neromidnight @jrettsch This is due to 4K monitors having the Screen DPI set to something higher than 100%. Essentially the window is too small and Discord will not draw to a window smaller than 768x432.

I am releasing a new version that will automatically scale the window's minimum size to the monitor's set DPI Scale.
