### ISSUE TITLE
Changeable scale

### ISSUE THREAD

**Issue by kvq** [flamewave000/discord-overlay#8]
For FullHD screen on 125% scale, discord overlay takes quite some space on the screen and also scaling seems to cause some render glitches. https://i.imgur.com/tdoyBvk.png
Would be great if there's option to scale down the overlay.

**Comment by flamewave000** [comment]
Unfortunately, I am unable to correct this issue. Discord scales its rendering up with the Screen's scale and I am unable to change that.

As for the render glitch, that is due to the pixel being the same colour as the Transparency Colour. This can sometimes happen with the icons users choose. I would suggest adjusting the Transparency colour if this is an issue for you.
